"""this is another migration

Revision ID: 6883ba15b90c
Revises: 6ac404a95794
Create Date: 2023-06-19 17:51:02.302602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6883ba15b90c'
down_revision = '6ac404a95794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_price', sa.Integer(), nullable=True))
        batch_op.alter_column('gh_post',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('city')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('qr_code')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.alter_column('gh_post',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('event_price')

    # ### end Alembic commands ###
