"""another migration

Revision ID: 7f91014e0def
Revises: 6883ba15b90c
Create Date: 2023-06-19 18:22:03.815291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f91014e0def'
down_revision = '6883ba15b90c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('event_category', sa.String(length=200), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.drop_column('image_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.drop_column('event_category')
        batch_op.drop_column('poster')

    # ### end Alembic commands ###
